// === [2026-09-10] 新增文件：惠享通政策数据外置 ===
// 本文件集中存放所有"会变的政策数据"：标准金额 L、政策链接 SRC、福利条目 POLICIES。
// 改政策（金额/条件/材料/入口/路径/链接）只改这里，不用碰全民福利计算器.html 的渲染逻辑。
// 加载方式：全民福利计算器.html 用 <script src="policies.js"> 经典脚本引入，file:// 双击与 http 部署均可用。

// 各地标准金额（money 字段用于金额估算汇总；带 M 后缀为数值）
const L = {
  dg:{ unemp:'2070元/月（按最低工资2300的90%，最长24个月）', unempM:2070,
       dibao:'1260元/人·月', dibaoM:1260, edge:'1890元/人·月', edgeM:1890, special:'2016元/人·月', specialM:2016 },
  sz:{ unemp:'2268元/月（最低工资2520的90%，最长24个月）', unempM:2268,
       dibao:'1535元/人·月', dibaoM:1535, edge:'2345元/月', edgeM:2345, special:'2501元/月', specialM:2501 },
  gz:{ unemp:'2250元/月（最低工资90%，最长24个月）', unempM:2250, dibao:'按广州市最新标准', edge:'按广州市标准', special:'按广州市标准' }
};

// 政策链接（官方文件/平台入口）
const SRC = {
  dg_unemp:'https://12345.dg.cn/external/operationInfo?guideId=1s202408210858227476669025',
  dg_flex:'https://dghrss.dg.gov.cn/gkmlpt/content/4/4576/post_4576906.html',
  dg_dibao:'https://mzj.dg.gov.cn/gkmlpt/content/4/4544/post_4544326.html',
  sz_dibao:'https://mzj.sz.gov.cn/gkmlpt/content/12/12809/post_12809638.html',
  sz_old:'https://mzj.sz.gov.cn/gkmlpt/content/12/12779/mpost_12779676.html',
  gz_baby:'https://www.gz.gov.cn/zt/shb/content/post_10710793.html',
  gz_hr:'https://rsj.gz.gov.cn/',
  talent_dg:'https://dghrss.dg.gov.cn/zcfg/zcjd/content/post_4558789.html',
  talent_sz:'http://www.zzb.sz.gov.cn/zgdongtai/rencai/content/post_1945066.html',
  talent_gz:'https://www.gz.gov.cn/zwgk/zdly/jycy/gzdt/content/post_10735170.html',
  gz_hp:'https://www.hp.gov.cn/xwzx/zwyw/content/post_10888298.html',
  gz_ns:'https://www.gz.gov.cn/zwfw/zxfw/jyfw/content/post_10873237.html',
  skill_gd:'https://hrss.gd.gov.cn/'
};

// 福利条目：每条含触发条件 test(i) 与全部展示字段。
// 字段说明：
//   test(i)        必填，返回 bool，决定是否对该处境展示
//   cat / nm       类目 / 名称（静态）
//   ds / cond / doc / apptxt / steps / app  展示文本（静态，或接收 (i,c) 的函数）
//   amt / money / per / cash / link  金额与链接：可为静态值，或 (i,c)=> 动态计算
//     - amt  展示用金额字符串
//     - money 数值（用于年预估汇总），无则 null
//     - per  'month' | 'year' | 'once'
//     - cash false 表示非现金福利（代缴/优待/免费），不计入金额汇总
const POLICIES = [
  { id:'unemp_jin', cat:'失业保障',
    test:i=> i.employ==='unemployed'||i.employ==='flexible',
    nm:'失业保险金',
    amt:(i,c)=>L[c].unemp, money:(i,c)=>L[c].unempM, per:'month',
    ds:'非本人意愿中断就业、失业前缴费满1年、已办失业登记即可申领；领取期间医保由失业保险基金代缴',
    cond:'① 非本人意愿中断就业（辞退/合同到期不续等）<br>② 失业前累计缴费满1年<br>③ 已办失业登记并有求职意愿',
    doc:'身份证、社保卡、解除/终止劳动合同证明、失业登记证明、本人银行卡',
    app:'https://si.12333.gov.cn/', apptxt:'国家社保服务平台（搜「失业保险金申领」）',
    steps:'打开「粤省事」→ 首页「社保·就业」→「失业」→「失业金待遇申领」（或在搜索框直接粘贴标准名「失业保险金申领」）→ 刷脸认证、填本人银行卡号 → 审核通过次月起按月发放到卡',
    link:(i,c)=>SRC.dg_unemp },

  { id:'unemp_yb', cat:'失业保障',
    test:i=> i.employ==='unemployed',
    nm:'失业期间医保代缴', cash:false,
    amt:'个人0元，失业保险基金全额代缴',
    ds:'领失业金期间，你的职工医保由失业保险基金代缴，个人不掏钱；门诊/住院报销待遇不断档，每月约省数百元',
    cond:'正在按月领取失业保险金（医保多数地区随失业金自动关联代缴）',
    doc:'通常无需材料、系统自动关联；以灵活就业身份续保的凭社保卡办理',
    app:'https://si.12333.gov.cn/', apptxt:'国家社保服务平台 / 粤省事（查「医保缴费状态」）',
    steps:'领失业金后医保多数地区自动代缴、无需申请；在「粤省事→医保」查缴费记录确认；若显示断缴，带社保卡到参保地医保经办窗口补关联代缴',
    link:(i,c)=>SRC.dg_unemp },

  { id:'unemp_yanglao', cat:'失业保障',
    test:i=> i.employ==='unemployed'||i.employ==='flexible',
    nm:'养老保险续接（灵活就业续缴）', cash:false,
    amt:'不停保·年限累计·可申社保补贴',
    ds:'失业或灵活就业期间，职工养老可转灵活就业身份个人续缴，缴费年限累计不中断；就业困难人员续缴还能同步申请灵活就业社保补贴',
    cond:'失业/灵活就业期间自愿续缴；就业困难人员可同步申请灵活就业社保补贴',
    doc:'身份证、社保卡、银行卡（续缴）；就业困难认定证明（申补贴）',
    app:'https://si.12333.gov.cn/', apptxt:'国家社保服务平台 / 粤省事（搜「灵活就业人员养老保险缴费」）',
    steps:'「粤省事→社保·就业→灵活就业人员养老保险缴费」按年/月续缴；就业困难人员另在政务服务网搜"灵活就业社保补贴"申领月补',
    link:(i,c)=>SRC.dg_flex },

  { id:'flex_sub', cat:'失业保障',
    test:i=> i.employ==='flexible'&&i.hard,
    nm:'灵活就业社保补贴',
    amt:'600元/月，最长3年', money:600, per:'month',
    ds:'经认定的就业困难人员以灵活就业身份参保，按600元/月补贴（距退休不足5年可延至退休）',
    cond:'经认定的就业困难人员（4050、残疾、低保家庭等）以灵活就业身份参保',
    doc:'身份证、社保卡、就业困难人员认定证明、灵活就业证明、本人银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「灵活就业社保补贴」）',
    steps:'广东政务服务网搜"灵活就业社保补贴" → 选参保地 → 上传就业困难认定 + 社保缴费凭证 → 社区/街道初审公示后按月发放',
    link:(i,c)=>SRC.dg_flex },

  { id:'dibao', cat:'收入兜底',
    test:i=> i.income==='low',
    nm:'最低生活保障',
    amt:(i,c)=>L[c].dibao, money:(i,c)=>L[c].dibaoM, per:'month',
    ds:'家庭人均收入低于当地低保标准，按月发放，差额补助',
    cond:'① 共同生活家庭成员人均收入低于当地低保标准<br>② 家庭财产状况符合规定<br>③ 本地户籍申请',
    doc:'户口本、身份证、家庭收入证明、财产状况声明书、本人银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「最低生活保障金给付」）',
    steps:'打开「粤省事」→「更多服务」→「社会救助」→「社会救助服务申请」→「最低生活保障申请」→ 刷脸认证、签署家庭经济状况核对授权书、上传户口本/身份证 → 提交后等街道入户核查、公示无异议后按月发放',
    link:(i,c)=> c==='sz'?SRC.sz_dibao:SRC.dg_dibao },

  { id:'special', cat:'收入兜底',
    test:i=> i.income==='low',
    nm:'特困人员供养',
    amt:(i,c)=>L[c].special, money:(i,c)=>L[c].specialM, per:'month',
    ds:'无劳动能力、无生活来源、无法定赡养人的特困人员，按月供养',
    cond:'无劳动能力、无生活来源、无法定赡养/抚养/扶养义务人，或义务人无履行能力',
    doc:'身份证、户口本、收入及财产核查材料、残疾或重病证明（如有）',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「特困人员供养」）',
    steps:'户籍地街道办民政窗口，或「粤省事」搜"特困人员供养" → 提交特困认定材料 → 入户核查 → 按月发放供养金',
    link:(i,c)=> c==='sz'?SRC.sz_dibao:SRC.dg_dibao },

  { id:'edge', cat:'收入兜底',
    test:i=> i.income==='edge',
    nm:'低保边缘/低收入家庭扶助',
    amt:(i,c)=>L[c].edge, money:(i,c)=>L[c].edgeM, per:'month',
    ds:'人均收入略高于低保线的边缘家庭，可享生活扶助与专项救助',
    cond:'家庭人均收入略高于当地低保标准（一般 1-1.5 倍），未纳入低保',
    doc:'户口本、身份证、家庭收入及支出证明、相关困难佐证材料',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「低收入家庭认定」）',
    steps:'户籍地街道办民政窗口，或「粤省事」搜"低收入家庭认定" → 提交收入支出证明 → 核查认定后享受专项救助',
    link:(i,c)=> c==='sz'?SRC.sz_dibao:SRC.dg_dibao },

  { id:'medical', cat:'医疗',
    test:i=> i.sick||i.income==='low',
    nm:'医疗救助 / 临时救助',
    amt:'按政策据实救助',
    ds:'因病致贫、突发重大困难的可申请医疗救助或临时救助，困难群众参保可获资助',
    cond:'低保/特困/低保边缘家庭，或因病致贫、因突发事件造成临时性困难',
    doc:'身份证、社保卡、医疗费用票据、诊断证明、家庭收入证明',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「医疗救助/临时救助」）',
    steps:'「粤省事」或政务服务网搜"医疗救助/临时救助" → 上传医疗票据或突发困难证明 → 医保局或民政办审核 → 救助金直拨',
    link:(i,c)=> c==='sz'?SRC.sz_dibao:SRC.dg_dibao },

  { id:'house', cat:'住房',
    test:i=> i.income!=='normal'||i.employ==='unemployed',
    nm:'公租房 / 保障性租赁住房',
    amt:'租金优惠或租赁补贴',
    ds:'低收入、新市民、青年人才等可申请公租房或保租房，租金低于市场价',
    cond:'中等偏下收入住房困难家庭、新就业无房青年、外来务工人员等（按当地准入条件）',
    doc:'身份证、户口本/居住证、收入证明、住房状况证明、婚姻状况证明',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「公租房申请」）',
    steps:'政务服务网搜"公租房申请" → 填收入与住房状况 → 轮候配租，或发放租赁补贴到银行卡',
    link:(i,c)=> c==='sz'?SRC.sz_old:SRC.dg_dibao },

  { id:'elder_allow', cat:'养老',
    test:i=> i.age==='elder'||i.elderHome,
    nm:'高龄老人津贴',
    amt:(i,c)=> c==='sz'?'70岁以上户籍 200-1000元/月':'按当地标准(通常70/80岁起)', money:(i,c)=> c==='sz'?200:null, per:'month',
    ds:'本地户籍高龄老人按月发放津贴，标准随年龄递增',
    cond:'本地户籍，80 岁以上（部分省份 70/90 岁起算）',
    doc:'身份证、户口本、本人银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「高龄津贴」）',
    steps:'户籍地村(居)委会或「粤省事」搜"高龄津贴" → 刷脸确认身份 → 多数地区免申即享、按月到账（部分地区需提交一次）',
    link:(i,c)=> SRC.sz_old },

  { id:'resident_pension', cat:'养老',
    test:i=> i.age==='elder',
    nm:'城乡居民基本养老保险',
    amt:'按档发放（广州基础养老金297元/月）',
    ds:'年满60岁、未享职工养老的可参保并按月领养老金',
    cond:'年满 60 周岁、未享受职工基本养老保险待遇、本地累计缴费满 15 年',
    doc:'身份证、户口本、社保卡、本人银行账户',
    app:'https://si.12333.gov.cn/', apptxt:'国家社保服务平台（搜「城乡居民养老保险待遇申领」）',
    steps:'户籍地社保所或「粤省事」搜"城乡居民养老保险待遇申领" → 满60岁提交申办 → 按月发放到社保卡/银行卡',
    link:(i,c)=> SRC.gz_hr },

  { id:'baby', cat:'育儿',
    test:i=> i.kids,
    nm:'国家育儿补贴',
    amt:'每孩每年3600元，发至3周岁', money:3600, per:'year',
    ds:'2026年起全面开放，无论几孩，每孩每年3600元至3岁，支付宝/穗好办等申领',
    cond:'拥有 3 周岁以下婴幼儿的婴幼儿监护人（含父母、祖辈等）',
    doc:'出生医学证明、户口本、监护人身份证、本人银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「育儿补贴」）',
    steps:'支付宝搜"国家育儿补贴"小程序，或「粤省事/穗好办」搜"育儿补贴" → 填婴幼儿与监护人信息、绑卡 → 按年发放到银行卡',
    link:(i,c)=> SRC.gz_baby },

  { id:'birth', cat:'育儿',
    test:i=> i.kids,
    nm:'生育津贴',
    amt:'按产假天数与缴费基数计发',
    ds:'职工或符合条件的失业人员分娩/终止妊娠可申领生育津贴',
    cond:'职工（或符合条件的失业人员）分娩/终止妊娠；连续缴费满当地规定月数',
    doc:'身份证、社保卡、生育服务证/生育登记、医疗费用票据、出院小结',
    app:'https://si.12333.gov.cn/', apptxt:'国家社保服务平台（搜「生育津贴申领」）',
    steps:'由单位经办人或本人通过「粤省事/i深圳/穗好办」搜"生育津贴申领" → 上传生育证明+出院小结 → 核拨给单位或个人',
    link:(i,c)=> SRC.gz_baby },

  { id:'disabled', cat:'残疾',
    test:i=> i.disabled,
    nm:'残疾人两项补贴',
    amt:'困难生活补贴 + 重度护理补贴（按月）',
    ds:'持残疾人证，困难残疾人发生活补贴、重度残疾人发护理补贴',
    cond:'持有效残疾人证；困难残疾人生活补贴 + 重度残疾人（三四级以上）护理补贴',
    doc:'残疾人证、身份证、户口本、低保证明（如申请困难生活补贴）',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「残疾人两项补贴」）',
    steps:'户籍地街道残联或「粤省事」搜"残疾人两项补贴" → 上传残疾人证 → 审核通过后按月发放到银行卡',
    link:(i,c)=> SRC.sz_old },

  { id:'vet_pension', cat:'退役',
    test:i=> i.vet,
    nm:'优抚对象抚恤/补助',
    amt:'按身份与服役情况定',
    ds:'退役军人和优抚对象可享定期抚恤、医疗优先、创业扶持等',
    cond:'退役军人、烈士遗属、因公牺牲军人遗属、病故军人遗属等优抚对象',
    doc:'身份证、退役证/优抚证、户口本、本人银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「优抚对象抚恤补助」）',
    steps:'户籍地退役军人事务局/服务中心，或「粤省事」搜"优抚金" → 提交优抚证 → 按月发放抚恤补助',
    link:(i,c)=> SRC.gz_hr },

  { id:'vet_free', cat:'退役',
    test:i=> i.vet,
    nm:'退役军人优待（非现金）', cash:false,
    amt:'公交免费·医疗优先·景区免票',
    ds:'凭退役军人优待证可享公共交通免费/半价、公立医疗优先就诊、景区免门票、部分银行手续费减免等优待，不发现金但天天省',
    cond:'持有退役军人优待证（或优抚证）',
    doc:'退役军人优待证、身份证',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「退役军人优待证」）',
    steps:'到户籍地退役军人事务局/服务中心申领优待证 → 持证享受公交、医疗、文旅等优待',
    link:(i,c)=> SRC.gz_hr },

  { id:'dg_talent_intro', cat:'人才',
    test:i=> i.edu!=='below'&&i.city==='dg',
    nm:'新引进补贴',
    amt:'最高10万元(E类)', money:100000, per:'once',
    ds:'2025年后引进、经认定E类人才，分2年发放',
    cond:'新引进且经认定的 E 类及以上人才，与东莞用人单位签订 ≥1 年劳动合同并参保',
    doc:'身份证、学历/学位证、劳动合同、社保参保证明、人才认定证书、银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「东莞新引进人才补贴」）',
    steps:'先「粤省事」或东莞市人社局完成人才认定 → 再搜"东莞新引进人才补贴" → 传劳动合同/社保 → 分2年发放',
    link:(i,c)=> SRC.talent_dg },

  { id:'dg_talent_rent', cat:'人才',
    test:i=> i.edu!=='below'&&i.city==='dg',
    nm:'租房补贴',
    amt:'最高1.8万元', money:18000, per:'once',
    ds:'安居租房补贴',
    cond:'经认定的 E 类及以上人才、本人在莞无房、未享受其他住房政策',
    doc:'身份证、人才认定证书、劳动合同、住房状况承诺书、租赁合同/房租发票',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「东莞人才租房补贴」）',
    steps:'「粤省事」搜"东莞人才租房补贴" → 传人才认定 + 无房承诺/租房合同 → 审核后一次性发放',
    link:(i,c)=> SRC.talent_dg },

  { id:'dg_talent_phd', cat:'人才',
    test:i=> i.edu==='bs'&&i.city==='dg',
    nm:'学历提升资助(博士)',
    amt:'3万元', money:30000, per:'once',
    ds:'在莞工作期间取得博士学位',
    cond:'在莞工作期间在职取得博士学位',
    doc:'博士学位证书、劳动合同、社保参保证明、银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「东莞学历提升资助」）',
    steps:'「粤省事」搜"东莞学历提升资助" → 上传博士学位证 + 在莞工作证明 → 一次性发放3万元',
    link:(i,c)=> SRC.talent_dg },

  { id:'sz_talent_intro', cat:'人才',
    test:i=> i.edu!=='below'&&i.city==='sz'&&i.hukou!=='new',
    nm:'新引进人才入户补贴',
    amt:(i,c)=>{ const hk={bk:30000,ss:50000,bs:100000,bsh:100000}[i.edu]; return (hk/10000)+'万元（一次性）'; },
    money:(i,c)=>({bk:30000,ss:50000,bs:100000,bsh:100000}[i.edu]), per:'once',
    ds:'按学历分档（博士最高10万）',
    cond:'应届/新引进落户深圳、在深缴满 6 个月社保、未享受过同类人才政策',
    doc:'身份证、毕业证/学位证、落户证明、社保清单、本人银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「深圳新引进人才补贴」）',
    steps:'下载「i深圳」APP → 搜"新引进人才补贴" → 落户+社保满6月后提交学历证明 → 一次性发放',
    link:(i,c)=> SRC.talent_sz },

  { id:'sz_young_rent', cat:'人才',
    test:i=> i.edu!=='below'&&i.city==='sz'&&i.hukou!=='new',
    nm:'青年安居补贴',
    amt:'税后1000元/月×最长24个月', money:1000, per:'month',
    ds:'或申请租金6折过渡住房，二选一',
    cond:'新引进 35 周岁以下、在深未拥有自有住房、未享受其他住房政策',
    doc:'身份证、劳动合同、社保清单、无房证明、银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「深圳青年安居补贴」）',
    steps:'「i深圳」搜"青年安居补贴" → 填无房声明 + 劳动合同 → 按月发放（最长24个月）',
    link:(i,c)=> SRC.talent_sz },

  { id:'gz_talent_settle', cat:'人才',
    test:i=> i.edu!=='below'&&i.city==='gz',
    nm:'落户生活/安家补贴',
    amt:(i,c)=>{ const life={bk:30000,ss:60000,bs:200000,bsh:300000}[i.edu]; return '最高'+(life/10000)+'万元'; },
    money:(i,c)=>({bk:30000,ss:60000,bs:200000,bsh:300000}[i.edu]), per:'once',
    ds:'本科及以上落户秒批；博士另有市安家费',
    cond:'本科及以上学历新入户广州、在穗就业并参保；按学历分档',
    doc:'身份证、毕业证/学位证、户口本、社保清单、银行卡',
    app:'https://www.gdzwfw.gov.cn/', apptxt:'广东政务服务网（搜「广州人才落户补贴」）',
    steps:'下载「穗好办」APP → 搜"人才落户补贴" → 落户+在穗参保后提交材料 → 审核发放',
    link:(i,c)=> SRC.talent_gz },

  { id:'skill_up', cat:'技能',
    test:i=> i.employ==='employed'||i.employ==='flexible',
    nm:'职业技能提升补贴',
    amt:'800–2400元（按证书等级，考到证即领）', money:1500, per:'once',
    ds:'在职期间考取《广东省职业技能提升补贴目录》内证书可申领，补贴随等级递增，与学历、户籍、来莞几年均无关。⚠️ 广东此项（失业保险技能提升补贴）曾阶段性暂停受理，办理前先在粤省事确认该事项是否开放',
    cond:'① 在职并正常缴纳失业/社保满一定期限（现行阶段性放宽至累计满 12 个月）<br>② 取得补贴目录内职业技能等级证书（初级/中级/高级/技师）<br>③ 证书核发之日起 12 个月内申请<br>④ 每人每年最多可领 3 次、且须不同工种',
    doc:'身份证、社保卡、职业技能等级证书、社保参保证明、本人银行卡',
    app:'https://ggfw.hrss.gd.gov.cn/', apptxt:'粤省事 / 广东人社 APP（搜「失业保险技能提升补贴申领」）',
    steps:'打开「粤省事」微信小程序 → 左上角切换城市为你的参保地 → 首页「社保·就业」→「失业」→「失业保障-失业保险技能提升补贴申领」→ 录入证书编号按提示办理（也可在「广东人社」APP 或省人社厅平台 ggfw.hrss.gd.gov.cn 搜同名事项办理）',
    link:(i,c)=> SRC.skill_gd },

  { id:'skill_free', cat:'技能',
    test:i=> i.employ==='employed'||i.employ==='flexible',
    nm:'免费职业技能培训', cash:false,
    amt:'政府补贴性培训，个人0元',
    ds:'人社部门组织的补贴性职业技能培训（如粤菜师傅、南粤家政、工业机器人等）对符合条件人员免费，区别于"考到证再领"的技能提升补贴',
    cond:'本地户籍或在本地的就业重点群体（失业人员、农民工、在职职工等），按项目条件',
    doc:'身份证、社保卡、就业/失业证明（按项目）',
    app:'https://ggfw.hrss.gd.gov.cn/', apptxt:'广东人社APP / 粤省事（搜「补贴性职业技能培训」）',
    steps:'「广东人社」APP或省人社平台搜"补贴性职业技能培训" → 选免费项目报名 → 培训合格发证（不收费）',
    link:(i,c)=> SRC.skill_gd }
];
